### ISSUE TITLE
[Enhancement] Use /dev/shm for speeding up Mikado (through the --shm CLI switch)

### ISSUE THREAD

**Issue by lucventurini** [EI-CoreBioinformatics/minos#50]
While I was debugging things with @ljyanesm today on the Mikado side, I realised that putting the Mikado DB into `/dev/shm` speeds up `mikado pick` by several times (from 26 minutes to 3, that's not a typo, for a minos run on *A. thaliana* chromosome 1).

Mikado supports this through the `--shm` command line switch in `pick`. The database gets copied automatically to `/dev/shm` and deleted at the end of the run, if Mikado does not crash ungracefully or is not killed.

I do not think this should be the default behaviour in Minos, but it sounds like a potential easy enhancement for the pipeline.

**Comment by gemygk** [comment]
@lucventurini
yes, it is useful. The option `--shm` can be added in. 
I think the only downside I can think of is that the `/dev/shm` (which is only half the size of the ram or smaller) can get used either due to the size of Mikado DB itself or by other processors using them causing the DB creation to fail.

**Comment by ljyanesm** [comment]
The usage of /dev/shm could be accounted for by reserving the size of the DB as part of the RAM usage of the process, we should ideally cleanup afterwards even in the event mikado terminates ungracefully as this could leave the DB files on /dev/shm on the host where it was executed.

**Comment by lucventurini** [comment]
> The usage of /dev/shm could be accounted for by reserving the size of the DB as part of the RAM usage of the process, we should ideally cleanup afterwards even in the event mikado terminates ungracefully as this could leave the DB files on /dev/shm on the host where it was executed.

Yes, agreed. However, a problem is that Mikado currently does not allow to specify the name of the database for /dev/shm; it is a temporary file whose name gets generated automatically. I think it is sensible to avoid clashing, but it complicates things for an external manager. Suggestions?

**Comment by ljyanesm** [comment]
I've reran using annotation-workshop-preparation mikado with 8 and 16 processes on shm and noshm but didn't see such a large difference, shm ~2m30s noshm ~4m this was consistent on both counts of processes.

There seems to be some speedup when using shm, but it doesn't seem as large as initially suggested. This could be down to the db being on the shared filesystem instead of locally present (which would happen when running with shm) but beyond that with the metrics I have its not possible to tell. The initial numbers on this issue seem to indicate that occasionally there might slowdowns which would be attributable to factors external to mikado.

**Comment by lucventurini** [comment]
> Edit: These measurements were done against "TEST/Chr1-11M-12M" which might not coincide with what was measured previously

I was measuring in TEST/Chr1

**Comment by ljyanesm** [comment]
In that case, although it is clearly much better to use shm, it seems a bit odd that for such a small region mikado takes a similar amount of time than for a larger one only when using shm.

**Comment by lucventurini** [comment]
Closing this as the issue in our case was the NFS, and EI-CoreBioinformatics/mikado@40f887b should have solved this for good.
